// Ported from taffy/src/compute/float.rs
// Computes the position of floats in a block formatting context
//
// Here are the precise rules that govern the behavior of floats:
//
// 1. The left outer edge of a left-floating box may not be to the left of the left edge of its containing block.
//    An analogous rule holds for right-floating elements.
// 2. If the current box is left-floating, and there are any left-floating boxes generated by elements earlier in
//    the source document, then for each such earlier box, either the left outer edge of the current box must be to
//    the right of the right outer edge of the earlier box, or its top must be lower than the bottom of the earlier box.
//    Analogous rules hold for right-floating boxes.
// 3. The right outer edge of a left-floating box may not be to the right of the left outer edge of any right-floating
//    box that is next to it. Analogous rules hold for right-floating elements.
// 4. A floating box's outer top may not be higher than the top of its containing block.
// 5. The outer top of a floating box may not be higher than the outer top of any block or floated box generated by
//    an element earlier in the source document.
// 6. The outer top of an element's floating box may not be higher than the top of any line-box containing a box
//    generated by an element earlier in the source document.
// 7. A left-floating box that has another left-floating box to its left may not have its right outer edge to the
//    right of its containing block's right edge.
// 8. A floating box must be placed as high as possible.
// 9. A left-floating box must be put as far to the left as possible, a right-floating box as far to the right as
//    possible. A higher position is preferred over one that is further to the left/right.
//
// https://www.w3.org/TR/CSS22/visuren.html#floats

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Marius.Winter.Taffy
{
    /// <summary>
    /// An empty "slot" that avoids floats that is suitable for non-floated content
    /// to be laid out into
    /// </summary>
    public struct ContentSlot
    {
        /// <summary>The id of the segment that the slot starts in</summary>
        public int? SegmentId;
        /// <summary>The x position of the start of the slot</summary>
        public float X;
        /// <summary>The y position of the start of the slot</summary>
        public float Y;
        /// <summary>The width of the slot</summary>
        public float Width;
        /// <summary>The height of the slot</summary>
        public float Height;
    }

    /// <summary>
    /// A floated box
    /// </summary>
    public struct PlacedFloatedBox
    {
        /// <summary>The width of the box</summary>
        public float Width;
        /// <summary>The height of the box</summary>
        public float Height;
        /// <summary>
        /// Horizontal distance from the edge of the container that the box is floated towards
        /// (distance from the left for left floats, from the right for right floats)
        /// </summary>
        public float XInset;
        /// <summary>Vertical distance from top edge of the container</summary>
        public float Y;
    }

    /// <summary>
    /// A non-overlapping horizontal segment of the Block Formatting Context container
    /// </summary>
    internal struct Segment
    {
        /// <summary>The vertical start point of the segment</summary>
        public float YStart;
        /// <summary>The vertical end point of the segment</summary>
        public float YEnd;
        /// <summary>Left inset in slot 0. Right inset in slot 1.</summary>
        public float Inset0;
        public float Inset1;

        /// <summary>Whether the segment can fit the passed floated box (in the horizontal axis)</summary>
        public bool FitsFloatWidth(Size<float> floatedBox, FloatDirection direction, float bfcWidth)
        {
            int slot = (int)direction;
            float insetForSlot = slot == 0 ? Inset0 : Inset1;
            return insetForSlot == 0.0f || (bfcWidth - floatedBox.Width - InsetSum()) >= 0.0f;
        }

        /// <summary>The total space taken up by both insets</summary>
        public float InsetSum()
        {
            return Inset0 + Inset1;
        }

        public float GetInset(int slot) => slot == 0 ? Inset0 : Inset1;
        public void SetInset(int slot, float value)
        {
            if (slot == 0) Inset0 = value;
            else Inset1 = value;
        }

        /// <summary>Whether the y range contains the given value (half-open: [start, end))</summary>
        public bool YContains(float y)
        {
            return y >= YStart && y < YEnd;
        }
    }

    /// <summary>
    /// Helper type for placing a single floated box.
    /// Given a pinned starting y position, this type helps determine if there is any x position
    /// such that there is sufficient horizontal space for the box across its entire height.
    /// </summary>
    internal struct FloatFitter
    {
        /// <summary>The overall width of the Block Formatting Context</summary>
        public float BfcWidth;
        /// <summary>The total height of the set of segments currently being considered</summary>
        public double SlotHeight;
        /// <summary>The union of the insets of the set of segments currently being considered</summary>
        public float Inset0;
        public float Inset1;

        /// <summary>Create a new FloatFitter</summary>
        public FloatFitter(float bfcWidth, float slotHeight, float[] containingBlockInsets)
        {
            BfcWidth = bfcWidth;
            SlotHeight = slotHeight;
            Inset0 = containingBlockInsets[0];
            Inset1 = containingBlockInsets[1];
        }

        /// <summary>Union the insets of another segment. This is a "max" of the insets on each side.</summary>
        public void UnionInsets(float inset0, float inset1)
        {
            Inset0 = MathF.Max(Inset0, inset0);
            Inset1 = MathF.Max(Inset1, inset1);
        }

        /// <summary>
        /// Given the currently accounted for insets, check whether there is an x position
        /// such that the box fits horizontally
        /// </summary>
        public bool FitsHorizontally(float width)
        {
            return (Inset0 == 0.0f && Inset1 == 0.0f) || BfcWidth - Inset0 - Inset1 - width >= 0.0f;
        }

        /// <summary>Add the height of another segment.</summary>
        public void AddHeight(float height)
        {
            SlotHeight += height;
        }

        /// <summary>Given the currently accounted for height, check whether the box fits vertically</summary>
        public bool FitsVertically(float height)
        {
            return SlotHeight >= height;
        }

        public float GetInset(int slot) => slot == 0 ? Inset0 : Inset1;
    }

    /// <summary>
    /// A context for placing floated boxes
    /// </summary>
    public class FloatContext
    {
        /// <summary>
        /// The available space constraint that applies to the root Block Formatting Context
        /// for which this FloatContext manages floats.
        /// </summary>
        private float _availableWidth;

        /// <summary>Whether the float context contains any floats</summary>
        private bool _hasFloats;

        /// <summary>A list of left-floated boxes within the context</summary>
        private readonly List<PlacedFloatedBox> _leftFloats = new List<PlacedFloatedBox>();

        /// <summary>A list of right-floated boxes within the context</summary>
        private readonly List<PlacedFloatedBox> _rightFloats = new List<PlacedFloatedBox>();

        /// <summary>
        /// A list of non-overlapping horizontal "segments" within the context.
        /// Each segment has the same available width for its entire height.
        /// </summary>
        private readonly List<Segment> _segments = new List<Segment>();

        /// <summary>
        /// A closed-open range indicating which segment the last placed float
        /// was placed (on each side). Index 0 = left, Index 1 = right.
        /// </summary>
        private int _lastPlacedFloatStart0;
        private int _lastPlacedFloatEnd0;
        private int _lastPlacedFloatStart1;
        private int _lastPlacedFloatEnd1;

        /// <summary>Create a new empty FloatContext</summary>
        public FloatContext()
        {
        }

        /// <summary>Whether the float context contains any floats</summary>
        public bool HasFloats()
        {
            return _hasFloats;
        }

        /// <summary>Whether the float context contains any floats that extend to or below min_y</summary>
        public bool HasActiveFloats(float minY)
        {
            if (!_hasFloats) return false;
            float lastEnd = _segments.Count > 0 ? _segments[_segments.Count - 1].YEnd : 0.0f;
            return lastEnd > minY;
        }

        /// <summary>Set the width of the FloatContext</summary>
        public void SetWidth(float availableWidth)
        {
            _availableWidth = availableWidth;
        }

        /// <summary>Returns a read-only list of placed left floats</summary>
        public IReadOnlyList<PlacedFloatedBox> LeftFloats => _leftFloats;

        /// <summary>Returns a read-only list of placed right floats</summary>
        public IReadOnlyList<PlacedFloatedBox> RightFloats => _rightFloats;

        private int GetLastPlacedStart(int slot) => slot == 0 ? _lastPlacedFloatStart0 : _lastPlacedFloatStart1;
        private int GetLastPlacedEnd(int slot) => slot == 0 ? _lastPlacedFloatEnd0 : _lastPlacedFloatEnd1;

        private void SetLastPlacedStart(int slot, int value)
        {
            if (slot == 0) _lastPlacedFloatStart0 = value;
            else _lastPlacedFloatStart1 = value;
        }

        private void SetLastPlacedEnd(int slot, int value)
        {
            if (slot == 0) _lastPlacedFloatEnd0 = value;
            else _lastPlacedFloatEnd1 = value;
        }

        /// <summary>
        /// Divide a segment into two segments so that a new float can be placed and have its
        /// vertical start and end at exact segment boundaries
        /// </summary>
        private void SubdivideSegment(int idx, float divideAtY)
        {
            var oldSegment = _segments[idx];
            Debug.Assert(oldSegment.YContains(divideAtY) && oldSegment.YStart != divideAtY);

            var newSegment = new Segment
            {
                Inset0 = oldSegment.Inset0,
                Inset1 = oldSegment.Inset1,
                YStart = divideAtY,
                YEnd = oldSegment.YEnd
            };
            oldSegment.YEnd = divideAtY;
            _segments[idx] = oldSegment;
            _segments.Insert(idx + 1, newSegment);
        }

        /// <summary>Update the last placed float start and end values</summary>
        private void UpdateLastPlacedFloat(FloatDirection direction, int placementStart, int placementEnd)
        {
            int slot = (int)direction;
            SetLastPlacedStart(slot, Math.Max(GetLastPlacedStart(slot), placementStart));
            SetLastPlacedEnd(slot, Math.Max(GetLastPlacedEnd(slot), placementEnd));
        }

        /// <summary>Position a floated box within the context, returning the (x, y) coordinates</summary>
        public Point<float> PlaceFloatedBox(
            Size<float> floatedBox,
            float minY,
            float[] containingBlockInsets,
            FloatDirection direction,
            Clear clear)
        {
            _hasFloats = true;

            var placed = PlaceFloatedBoxInner(floatedBox, minY, containingBlockInsets, direction, clear);

            float xInset = placed.XInset;
            float y = placed.Y;
            switch (direction)
            {
                case FloatDirection.Left:
                    _leftFloats.Add(placed);
                    return new Point<float>(xInset, y);
                case FloatDirection.Right:
                    _rightFloats.Add(placed);
                    return new Point<float>(_availableWidth - xInset - floatedBox.Width, y);
                default:
                    throw new ArgumentOutOfRangeException(nameof(direction));
            }
        }

        /// <summary>Inner implementation of float placement, split into a separate function so that it can early-return</summary>
        private PlacedFloatedBox PlaceFloatedBoxInner(
            Size<float> floatedBox,
            float minY,
            float[] containingBlockInsets,
            FloatDirection direction,
            Clear clear)
        {
            int slot = (int)direction;

            // Ensure that float:
            //    - Starts at or after the last placed float that was floated in the same direction as it
            //    - Respects "clear"
            int hwm;
            switch (clear)
            {
                case Clear.Left:
                {
                    int floatDirStart = GetLastPlacedStart(slot);
                    int leftEnd = GetLastPlacedEnd(0);
                    hwm = Math.Max(floatDirStart, leftEnd + 1);
                    break;
                }
                case Clear.Right:
                {
                    int floatDirStart = GetLastPlacedStart(slot);
                    int rightEnd = GetLastPlacedEnd(1);
                    hwm = Math.Max(floatDirStart, rightEnd + 1);
                    break;
                }
                case Clear.Both:
                {
                    int leftEnd = GetLastPlacedEnd(0);
                    int rightEnd = GetLastPlacedEnd(1);
                    hwm = Math.Max(leftEnd, rightEnd) + 1;
                    break;
                }
                case Clear.None:
                default:
                    hwm = GetLastPlacedStart(slot);
                    break;
            }

            // Ensure that float is placed in a segment at or below "min_y"
            int? startIdxNullable = null;
            for (int i = hwm; i < _segments.Count; i++)
            {
                if (_segments[i].YEnd > minY)
                {
                    startIdxNullable = i;
                    break;
                }
            }

            int startIdx = startIdxNullable ?? _segments.Count;
            float startY = minY;
            int endIdx = startIdx;

            // Loop over remaining segments, trying to place the float in a position
            // that has space to accommodate it.
            int? start;
            int? end;
            float placedInset;

            while (true)
            {
                // Start segment does not exist
                if (startIdx >= _segments.Count)
                {
                    start = null;
                    end = null;
                    placedInset = containingBlockInsets[slot];
                    break;
                }

                var startSegment = _segments[startIdx];

                // Candidate start segment doesn't have (horizontal) space for the float
                if (!startSegment.FitsFloatWidth(floatedBox, direction, _availableWidth))
                {
                    startIdx++;
                    endIdx = Math.Max(endIdx, startIdx);
                    continue;
                }

                startY = MathF.Max(startY, startSegment.YStart);
                float availableHeight = startSegment.YEnd - startY;
                var fitter = new FloatFitter(_availableWidth, availableHeight, containingBlockInsets);
                fitter.UnionInsets(startSegment.Inset0, startSegment.Inset1);

                // Inner loop to find end segment
                bool continueOuter = false;
                while (true)
                {
                    // End segment does not exist
                    if (endIdx >= _segments.Count)
                    {
                        float inset = fitter.GetInset(slot);
                        start = startIdx;
                        end = null;
                        placedInset = inset;
                        goto done;
                    }

                    var endSegment = _segments[endIdx];

                    // Check horizontal fit
                    fitter.UnionInsets(endSegment.Inset0, endSegment.Inset1);
                    if (!fitter.FitsHorizontally(floatedBox.Width))
                    {
                        startIdx++;
                        endIdx = Math.Max(endIdx, startIdx);
                        continueOuter = true;
                        break;
                    }

                    // Check vertical fit
                    if (endIdx != startIdx)
                    {
                        fitter.AddHeight(endSegment.YEnd - endSegment.YStart);
                    }
                    if (!fitter.FitsVertically(floatedBox.Height))
                    {
                        endIdx++;
                        continue;
                    }

                    float inset2 = fitter.GetInset(slot);
                    start = startIdx;
                    end = endIdx;
                    placedInset = inset2;
                    goto done;
                }

                if (continueOuter) continue;
            }

            done:

            // Short-circuit for zero-sized boxes
            if (floatedBox.Width == 0.0f || floatedBox.Height == 0.0f)
            {
                return new PlacedFloatedBox
                {
                    Width = floatedBox.Width,
                    Height = floatedBox.Height,
                    Y = startY,
                    XInset = placedInset,
                };
            }

            // Handle case where floated box is placed after all existing segments
            if (!start.HasValue)
            {
                float lastYEnd = _segments.Count > 0 ? _segments[_segments.Count - 1].YEnd : 0.0f;
                if (startY > lastYEnd)
                {
                    _segments.Add(new Segment { YStart = lastYEnd, YEnd = startY, Inset0 = 0.0f, Inset1 = 0.0f });
                }

                float adjustedStartY = MathF.Max(lastYEnd, startY);

                var insets = new Segment
                {
                    Inset0 = containingBlockInsets[0],
                    Inset1 = containingBlockInsets[1],
                    YStart = adjustedStartY,
                    YEnd = adjustedStartY + floatedBox.Height
                };
                if (slot == 0) insets.Inset0 += floatedBox.Width;
                else insets.Inset1 += floatedBox.Width;
                _segments.Add(insets);

                // Update last_placed_float
                int newStartIdx = _segments.Count - 1;
                int newEndIdx = newStartIdx + 1;
                UpdateLastPlacedFloat(direction, newStartIdx, newEndIdx);

                return new PlacedFloatedBox
                {
                    Width = floatedBox.Width,
                    Height = floatedBox.Height,
                    Y = adjustedStartY,
                    XInset = containingBlockInsets[slot],
                };
            }

            // Else unwrap the index of the segment that the start of the floating box is placed in
            startIdx = start.Value;

            // If the floated box doesn't start at the exact same y-offset as the segment it starts in, then
            // subdivide that segment into two segments at the y-offset that the floated box starts at, and increment
            // `start_idx` so that the floating box is placed in the second of the two segments.
            if (startY != _segments[startIdx].YStart)
            {
                SubdivideSegment(startIdx, startY);
                startIdx++;
                if (end.HasValue)
                {
                    end = end.Value + 1;
                }
            }

            int finalEndIdx;
            if (!end.HasValue)
            {
                float lastYEnd = _segments.Count > 0 ? _segments[_segments.Count - 1].YEnd : 0.0f;
                if (minY > lastYEnd)
                {
                    _segments.Add(new Segment { YStart = lastYEnd, YEnd = minY, Inset0 = 0.0f, Inset1 = 0.0f });
                }
                finalEndIdx = _segments.Count - 1;
            }
            else
            {
                finalEndIdx = end.Value;
                float endY = startY + floatedBox.Height;
                if (endY != _segments[finalEndIdx].YEnd)
                {
                    SubdivideSegment(finalEndIdx, endY);
                }
            }

            // Update inset for the range of segments that the float is placed in
            float placedInsetPlusWidth = placedInset + floatedBox.Width;
            for (int i = startIdx; i <= finalEndIdx; i++)
            {
                var seg = _segments[i];
                seg.SetInset(slot, placedInsetPlusWidth);
                _segments[i] = seg;
            }

            // Update last_placed_float
            UpdateLastPlacedFloat(direction, startIdx, finalEndIdx + 1);

            return new PlacedFloatedBox
            {
                Width = floatedBox.Width,
                Height = floatedBox.Height,
                Y = startY,
                XInset = placedInset
            };
        }

        /// <summary>Get the end segment of the last float on side(s) specified by the clear parameter (if any)</summary>
        private int? ClearedSegment(Clear clear)
        {
            return clear switch
            {
                Clear.Left => GetLastPlacedEnd(0),
                Clear.Right => GetLastPlacedEnd(1),
                Clear.Both => Math.Max(GetLastPlacedEnd(0), GetLastPlacedEnd(1)),
                Clear.None => null,
                _ => null,
            };
        }

        /// <summary>Get the bottom of lowest relevant float for the specific clear property</summary>
        public float? ClearedThreshold(Clear clear)
        {
            var segIdx = ClearedSegment(clear);
            if (!segIdx.HasValue) return null;
            int idx = Math.Max(1, segIdx.Value) - 1;
            if (idx < _segments.Count)
                return _segments[idx].YEnd;
            return null;
        }

        /// <summary>Search for a space suitable for laying out non-floated content into</summary>
        public ContentSlot FindContentSlot(
            float minY,
            float[] containingBlockInsets,
            Clear clear,
            int? after)
        {
            if (!HasActiveFloats(minY))
            {
                return new ContentSlot
                {
                    SegmentId = null,
                    X = containingBlockInsets[0],
                    Y = minY,
                    Width = _availableWidth - containingBlockInsets[0] - containingBlockInsets[1],
                    Height = float.PositiveInfinity,
                };
            }

            // The min starting segment index
            int atLeast = after.HasValue ? after.Value + 1 : 0;
            int clearedIdx = ClearedSegment(clear).HasValue ? ClearedSegment(clear)!.Value + 1 : 0;
            int hwm = Math.Max(atLeast, clearedIdx);

            int? startIdxNullable = null;
            for (int i = hwm; i < _segments.Count; i++)
            {
                if (_segments[i].YEnd > minY)
                {
                    startIdxNullable = i;
                    break;
                }
            }
            int startIdx = startIdxNullable ?? _segments.Count;

            if (startIdx < _segments.Count)
            {
                var segment = _segments[startIdx];
                float insetLeft = MathF.Max(segment.Inset0, containingBlockInsets[0]);
                float insetRight = MathF.Max(segment.Inset1, containingBlockInsets[1]);
                return new ContentSlot
                {
                    SegmentId = startIdx,
                    X = insetLeft,
                    Y = MathF.Max(segment.YStart, minY),
                    Width = _availableWidth - insetLeft - insetRight,
                    Height = float.PositiveInfinity,
                };
            }
            else
            {
                return new ContentSlot
                {
                    SegmentId = null,
                    X = containingBlockInsets[0],
                    Y = minY,
                    Width = _availableWidth - containingBlockInsets[0] - containingBlockInsets[1],
                    Height = float.PositiveInfinity,
                };
            }
        }
    }

    /// <summary>
    /// Context for computing the intrinsic width contribution of a set of floats
    /// </summary>
    public struct FloatIntrinsicWidthCalculator
    {
        /// <summary>The available width of the container</summary>
        private readonly AvailableSpace _availableWidth;
        /// <summary>The running total intrinsic width contribution</summary>
        private float _contribution;

        /// <summary>Create a new FloatIntrinsicWidthCalculator</summary>
        public FloatIntrinsicWidthCalculator(AvailableSpace availableWidth)
        {
            _availableWidth = availableWidth;
            _contribution = 0.0f;
        }

        /// <summary>Add a float to the computation</summary>
        public void AddFloat(float width, FloatDirection direction, Clear clear)
        {
            if (_availableWidth.IsDefinite())
            {
                // We will never hit this code path with definite available space
            }
            else if (_availableWidth == AvailableSpace.MinContent)
            {
                _contribution = MathF.Max(_contribution, width);
            }
            else // MaxContent
            {
                _contribution += width;
            }
        }

        /// <summary>Get the computed float contribution to intrinsic width</summary>
        public float Result()
        {
            return _contribution;
        }
    }
}
