// Ported from taffy/src/compute/grid/explicit_grid.rs
// Helper functions for initialising GridTrack's from styles
// This mainly consists of evaluating GridAutoTracks

using System;
using System.Collections.Immutable;

namespace Marius.Winter.Taffy
{
    /// <summary>The auto-repeat fit strategy to use</summary>
    public enum AutoRepeatStrategy
    {
        /// <summary>
        /// If the grid container has a definite size or max size in the relevant axis:
        /// then the number of repetitions is the largest possible positive integer that does not cause the grid to overflow the content
        /// box of its grid container.
        /// </summary>
        MaxRepetitionsThatDoNotOverflow,

        /// <summary>
        /// Otherwise, if the grid container has a definite min size in the relevant axis:
        /// then the number of repetitions is the smallest possible positive integer that fulfills that minimum requirement
        /// </summary>
        MinRepetitionsThatDoOverflow,
    }

    /// <summary>
    /// Helper functions for initialising explicit grid tracks
    /// </summary>
    public static class ExplicitGridUtils
    {
        /// <summary>
        /// Compute the number of rows and columns in the explicit grid
        /// </summary>
        public static (ushort numRepetitions, ushort gridTemplateTrackCount) ComputeExplicitGridSizeInAxis(
            Style style,
            float? autoFitContainerSize,
            AutoRepeatStrategy autoFitStrategy,
            Func<IntPtr, float, float> resolveCalcValue,
            AbsoluteAxis axis)
        {
            ImmutableList<GridTemplateComponent> template;
            switch (axis)
            {
                case AbsoluteAxis.Horizontal:
                    template = style.GetGridTemplateColumns();
                    break;
                case AbsoluteAxis.Vertical:
                    template = style.GetGridTemplateRows();
                    break;
                default:
                    template = style.GetGridTemplateColumns();
                    break;
            }

            if (template == null || template.Count == 0)
                return (0, 0);

            // If template contains no tracks, then there are trivially zero explicit tracks
            var trackCount = template.Count;

            // If there are any repetitions that contains no tracks, then the whole definition should be considered invalid
            // and we default to no explicit tracks
            foreach (var trackDef in template)
            {
                if (trackDef.Kind == GridTemplateComponent.GridTemplateComponentKind.Repeat && trackDef.Repetition!.TrackCount == 0)
                    return (0, 0);
            }

            // Compute the number of tracks generated by single track definition and repetitions with a fixed repetition count
            ushort nonAutoRepeatingTrackCount = 0;
            foreach (var trackDef in template)
            {
                if (trackDef.Kind != GridTemplateComponent.GridTemplateComponentKind.Repeat)
                {
                    nonAutoRepeatingTrackCount += 1;
                }
                else
                {
                    var rc = trackDef.Repetition!.Count;
                    if (!rc.IsAuto)
                    {
                        nonAutoRepeatingTrackCount += (ushort)(rc.CountValue * trackDef.Repetition.TrackCount);
                    }
                }
            }

            ushort autoRepetitionCount = 0;
            foreach (var trackDef in template)
            {
                if (trackDef.Kind == GridTemplateComponent.GridTemplateComponentKind.Repeat && trackDef.Repetition!.Count.IsAuto)
                    autoRepetitionCount++;
            }

            bool allTrackDefsHaveFixedComponent = true;
            foreach (var trackDef in template)
            {
                if (trackDef.Kind != GridTemplateComponent.GridTemplateComponentKind.Repeat)
                {
                    if (!trackDef.Single.HasFixedComponent())
                    {
                        allTrackDefsHaveFixedComponent = false;
                        break;
                    }
                }
                else
                {
                    foreach (var sf in trackDef.Repetition!.Tracks)
                    {
                        if (!sf.HasFixedComponent())
                        {
                            allTrackDefsHaveFixedComponent = false;
                            break;
                        }
                    }
                    if (!allTrackDefsHaveFixedComponent) break;
                }
            }

            bool templateIsValid =
                autoRepetitionCount == 0 || (autoRepetitionCount == 1 && allTrackDefsHaveFixedComponent);

            // If the template is invalid because it contains multiple auto-repetition definitions or it combines an auto-repetition
            // definition with non-fixed-size track sizing functions, then disregard it entirely and default to zero explicit tracks
            if (!templateIsValid)
                return (0, 0);

            // If there are no repetitions, then the number of explicit tracks is simply equal to the lengths of the track definition
            // vector (as each item in the Vec represents one track).
            if (autoRepetitionCount == 0)
                return (0, nonAutoRepeatingTrackCount);

            // Find the auto-repeat definition
            ImmutableList<MinMax<MinTrackSizingFunction, MaxTrackSizingFunction>>? repetitionTracks = null;
            foreach (var def in template)
            {
                if (def.Kind == GridTemplateComponent.GridTemplateComponentKind.Repeat && def.Repetition!.Count.IsAuto)
                {
                    repetitionTracks = def.Repetition.Tracks;
                    break;
                }
            }

            ushort repetitionTrackCount = (ushort)repetitionTracks!.Count;

            // Determine the number of repetitions
            ushort numRepetitions;
            if (!autoFitContainerSize.HasValue)
            {
                numRepetitions = 1;
            }
            else
            {
                float innerContainerSize = autoFitContainerSize.Value;
                float? parentSize = innerContainerSize;

                // ...treating each track as its max track sizing function if that is definite or as its minimum track sizing function
                // otherwise, flooring the max track sizing function by the min track sizing function if both are definite
                float TrackDefiniteValue(MinMax<MinTrackSizingFunction, MaxTrackSizingFunction> sizingFunction)
                {
                    var maxSize = sizingFunction.Max.DefiniteValue(parentSize, resolveCalcValue);
                    var minSize = sizingFunction.Min.DefiniteValue(parentSize, resolveCalcValue);
                    if (maxSize.HasValue)
                    {
                        var result = maxSize.Value;
                        if (minSize.HasValue)
                            result = MathF.Max(result, minSize.Value);
                        return result;
                    }
                    return minSize ?? 0f;
                }

                float nonRepeatingTrackUsedSpace = 0f;
                foreach (var trackDef in template)
                {
                    if (trackDef.Kind != GridTemplateComponent.GridTemplateComponentKind.Repeat)
                    {
                        nonRepeatingTrackUsedSpace += TrackDefiniteValue(trackDef.Single);
                    }
                    else
                    {
                        var rc = trackDef.Repetition!.Count;
                        if (!rc.IsAuto)
                        {
                            float sum = 0f;
                            foreach (var sf in trackDef.Repetition.Tracks)
                                sum += TrackDefiniteValue(sf);
                            nonRepeatingTrackUsedSpace += sum * rc.CountValue;
                        }
                    }
                }

                var gapStyle = ((IGridContainerStyle)style).Gap();
                float gapSize = gapStyle.GetAbs(axis).ResolveOrZero(innerContainerSize, resolveCalcValue);

                // Compute the amount of space that a single repetition of the repeated track list takes
                float perRepetitionTrackUsedSpace = 0f;
                foreach (var sf in repetitionTracks)
                    perRepetitionTrackUsedSpace += TrackDefiniteValue(sf);

                // We special case the first repetition here because the number of gaps in the first repetition
                // depends on the number of non-repeating tracks in the template
                ushort saturatedSub = (ushort)Math.Max(0, nonAutoRepeatingTrackCount + repetitionTrackCount - 1);
                float firstRepetitionAndNonRepeatingTracksUsedSpace = nonRepeatingTrackUsedSpace
                    + perRepetitionTrackUsedSpace
                    + (saturatedSub * gapSize);

                // If a single repetition already overflows the container then we return 1 as the repetition count
                // (the number of repetitions is floored at 1)
                if (firstRepetitionAndNonRepeatingTracksUsedSpace > innerContainerSize)
                {
                    numRepetitions = 1;
                }
                else
                {
                    float perRepetitionGapUsedSpace = repetitionTrackCount * gapSize;
                    float perRepetitionUsedSpace = perRepetitionTrackUsedSpace + perRepetitionGapUsedSpace;
                    float numRepetitionThatFit = (innerContainerSize
                        - firstRepetitionAndNonRepeatingTracksUsedSpace)
                        / perRepetitionUsedSpace;

                    // If the container size is a preferred or maximum size:
                    //   Then we return the maximum number of repetitions that fit into the container without overflowing.
                    // If the container size is a minimum size:
                    //   - Then we return the minimum number of repetitions required to overflow the size.
                    //
                    // In all cases we add the additional repetition that was already accounted for in the special-case computation above
                    numRepetitions = autoFitStrategy switch
                    {
                        AutoRepeatStrategy.MaxRepetitionsThatDoNotOverflow => (ushort)(Math.Floor(numRepetitionThatFit) + 1),
                        AutoRepeatStrategy.MinRepetitionsThatDoOverflow => (ushort)(Math.Ceiling(numRepetitionThatFit) + 1),
                        _ => 1,
                    };
                }
            }

            ushort gridTemplateTrackCount = (ushort)(nonAutoRepeatingTrackCount + (repetitionTrackCount * numRepetitions));
            return (numRepetitions, gridTemplateTrackCount);
        }

        /// <summary>
        /// Resolve the track sizing functions of explicit tracks, automatically created tracks, and gutters
        /// given a set of track counts and all of the relevant styles
        /// </summary>
        public static void InitializeGridTracks(
            ref ValueList<GridTrack> tracks,
            TrackCounts counts,
            Style style,
            AbsoluteAxis axis,
            Func<int, bool> trackHasItems)
        {
            // Extract styles
            ImmutableList<GridTemplateComponent> trackTemplate;
            ImmutableList<MinMax<MinTrackSizingFunction, MaxTrackSizingFunction>> autoTracks;
            LengthPercentage gap;
            switch (axis)
            {
                case AbsoluteAxis.Horizontal:
                    trackTemplate = style.GetGridTemplateColumns();
                    autoTracks = style.GetGridAutoColumns();
                    gap = ((IGridContainerStyle)style).Gap().Width;
                    break;
                case AbsoluteAxis.Vertical:
                    trackTemplate = style.GetGridTemplateRows();
                    autoTracks = style.GetGridAutoRows();
                    gap = ((IGridContainerStyle)style).Gap().Height;
                    break;
                default:
                    trackTemplate = style.GetGridTemplateColumns();
                    autoTracks = style.GetGridAutoColumns();
                    gap = ((IGridContainerStyle)style).Gap().Width;
                    break;
            }

            // Clear vector (in case this is a re-layout), reserve space for all tracks ahead of time to reduce allocations,
            // and push the initial gutter
            tracks.Clear();
            tracks.Add(GridTrack.Gutter(gap));

            int autoTrackCount = autoTracks.Count;

            // Create negative implicit tracks
            if (counts.NegativeImplicit > 0)
            {
                if (autoTrackCount == 0)
                {
                    CreateImplicitTracksAuto(ref tracks, counts.NegativeImplicit, gap);
                }
                else
                {
                    int offset = autoTrackCount - (counts.NegativeImplicit % autoTrackCount);
                    CreateImplicitTracksFromList(ref tracks, counts.NegativeImplicit, autoTracks, offset, gap);
                }
            }

            int currentTrackIndex = counts.NegativeImplicit;

            // Create explicit tracks
            // An explicit check against the count (rather than just relying on track_template being empty) is required here
            // because a count of zero can result from the track_template being invalid, in which case it should be ignored.
            if (counts.Explicit > 0 && trackTemplate != null && trackTemplate.Count > 0)
            {
                foreach (var trackComponent in trackTemplate)
                {
                    if (trackComponent.Kind != GridTemplateComponent.GridTemplateComponentKind.Repeat)
                    {
                        var sf = trackComponent.Single;
                        tracks.Add(GridTrack.New(sf.Min, sf.Max));
                        tracks.Add(GridTrack.Gutter(gap));
                        currentTrackIndex += 1;
                    }
                    else
                    {
                        var rc = trackComponent.Repetition!.Count;
                        if (rc.IsAuto)
                        {
                            int autoRepeatedTrackCount = counts.Explicit - (trackTemplate.Count - 1);
                            var repeatTracks = trackComponent.Repetition.Tracks;
                            int repeatTrackCount = repeatTracks.Count;

                            for (int i = 0; i < autoRepeatedTrackCount; i++)
                            {
                                var trackDef = repeatTracks[i % repeatTrackCount];
                                var track = GridTrack.New(trackDef.Min, trackDef.Max);
                                var gutter = GridTrack.Gutter(gap);

                                // Auto-fit tracks that don't contain should be collapsed.
                                if (rc.IsAutoFit && !trackHasItems(currentTrackIndex))
                                {
                                    track.Collapse();
                                    gutter.Collapse();
                                }

                                tracks.Add(track);
                                tracks.Add(gutter);
                                currentTrackIndex += 1;
                            }
                        }
                        else
                        {
                            ushort count = rc.CountValue;
                            var repeatTracks = trackComponent.Repetition.Tracks;
                            int repeatTrackCount = repeatTracks.Count;
                            int totalTracks = repeatTrackCount * count;

                            for (int i = 0; i < totalTracks; i++)
                            {
                                var sf = repeatTracks[i % repeatTrackCount];
                                tracks.Add(GridTrack.New(sf.Min, sf.Max));
                                tracks.Add(GridTrack.Gutter(gap));
                                currentTrackIndex += 1;
                            }
                        }
                    }
                }
            }

            int gridAreaTracks = (counts.NegativeImplicit + counts.Explicit) - currentTrackIndex;

            // Create positive implicit tracks
            ushort positiveCount = (ushort)(counts.PositiveImplicit + gridAreaTracks);
            if (autoTrackCount == 0)
            {
                CreateImplicitTracksAuto(ref tracks, positiveCount, gap);
            }
            else
            {
                CreateImplicitTracksFromList(ref tracks, positiveCount, autoTracks, 0, gap);
            }

            // Mark first and last grid lines as collapsed
            if (tracks.Count > 0)
            {
                tracks[0].Collapse();
                tracks[tracks.Count - 1].Collapse();
            }
        }

        /// <summary>Utility function for creating implicit tracks with AUTO sizing</summary>
        private static void CreateImplicitTracksAuto(ref ValueList<GridTrack> tracks, int count, LengthPercentage gap)
        {
            for (int i = 0; i < count; i++)
            {
                tracks.Add(GridTrack.New(MinTrackSizingFunction.AUTO, MaxTrackSizingFunction.AUTO));
                tracks.Add(GridTrack.Gutter(gap));
            }
        }

        /// <summary>Utility function for creating implicit tracks from a list of track sizing functions</summary>
        private static void CreateImplicitTracksFromList(
            ref ValueList<GridTrack> tracks,
            int count,
            ImmutableList<MinMax<MinTrackSizingFunction, MaxTrackSizingFunction>> autoTracks,
            int offset,
            LengthPercentage gap)
        {
            int autoTrackCount = autoTracks.Count;
            for (int i = 0; i < count; i++)
            {
                var trackDef = autoTracks[(i + offset) % autoTrackCount];
                tracks.Add(GridTrack.New(trackDef.Min, trackDef.Max));
                tracks.Add(GridTrack.Gutter(gap));
            }
        }
    }
}
